### ISSUE TITLE
AssertionError when running noc_captioner.py -i images_list.txt

### ISSUE THREAD

**Issue by dreamflasher** [vsubhashini/noc#9]
```
Computing features for images 0-9 of 10
Traceback (most recent call last):
  File "noc_captioner.py", line 569, in <module>
    main()
  File "noc_captioner.py", line 553, in main
    strategies=STRATEGIES, display_vocab=vocab_list)
  File "noc_captioner.py", line 286, in run_pred_iters
    run_pred_iter(pred_net, image_fc7, display_vocab, strategies=strategies)
  File "noc_captioner.py", line 199, in run_pred_iter
    captions, probs = predict_image_caption(net, mean_pool_fc7, vocab_list, strategy=strategy)
  File "noc_captioner.py", line 97, in predict_image_caption
    return predict_image_caption_beam_search(net, mean_pool_fc7, vocab_list, strategy)
  File "noc_captioner.py", line 174, in predict_image_caption_beam_search
    assert probs.shape[0] == len(vocab_list)
AssertionError

```

**Comment by vsubhashini** [comment]
Did you change the vocab file? (Or not download it?
surf_intersect_glove.txt)

**Comment by dreamflasher** [comment]
I exactly followed https://github.com/vsubhashini/noc
It doesn't say anything about downloading the vocab file there, where do I find it?

**Comment by dreamflasher** [comment]
Seems to be checked in to the repo? https://github.com/vsubhashini/noc/blob/recurrent/examples/noc/surf_intersect_glove.txt – or do I need a different one? I did a normal git clone…

**Comment by vsubhashini** [comment]
Yes that's the one. It's weird you should get the error.  Can you print the
length of the vocab_list and probs.shape and check what's different.
